### ISSUE TITLE
Glut OSD Interface + OpenGL renderer  crash in some games  

### ISSUE THREAD

**Issue by mrcmunir** [devmiyax/yabause#616]
I detected core crash in some games with  OpenGL renderer  + Glut OSD interface 
This not hapen when select software OSD interface or nanovg OSD interface 

This option are tested or are deprecated Compared with nanovg? .

I only see with gdb fail GI_

```
(gdb) bt
#0  0x0000007fb65bc4d8 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x0000007fb65bd8b4 in __GI_abort () at abort.c:79
#2  0x00000055557fcb50 in YglTMInit (w=640, h=512)
    at /home/jetson/yabause/yabause/src/ygles.c:509
#3  0x0000005555793308 in VIDOGLVdp2DrawStart ()
    at /home/jetson/yabause/yabause/src/vidogl.c:5328
#4  0x00000055557658e4 in vdp2VBlankOUT ()
    at /home/jetson/yabause/yabause/src/vdp2.c:896
#5  0x000000555576517c in Vdp2HBlankOUT ()
    at /home/jetson/yabause/yabause/src/vdp2.c:694
#6  0x00000055557bd768 in YabauseEmulate ()
    at /home/jetson/yabause/yabause/src/yabause.c:725
#7  0x00000055557bd2b8 in YabauseExec ()
    at /home/jetson/yabause/yabause/src/yabause.c:541
#8  0x0000005555656830 in PERQTHandleEvents ()
    at /home/jetson/yabause/yabause/src/qt/PerQt.c:51
#9  0x00000055556f3bd8 in YabauseThread::timerEvent(QTimerEvent*) (this=0x55567fb780) at /home/jetson/yabause/yabause/src/qt/YabauseThread.cpp:500
#10 0x0000007fb6c0ec50 in QObject::event(QEvent*) ()
    at /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#11 0x0000007fb7496f90 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#12 0x0000007fb749ece8 in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
#13 0x0000007fb6bdd438 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#14 0x0000007fb6c39444 in QTimerInfoList::activateTimers() ()
    at /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#15 0x0000007fb6c39cac in  () at /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#16 0x0000007fb5936c68 in g_main_context_dispatch ()
    at /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0
#17 0x0000007fb5936ec4 in  () at /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0
#18 0x0000000000000001 in  ()
```

**Comment by mrcmunir** [comment]
Solved and workaround are change to clang7 compiler for some reasone doesn't like gcc7
