### ISSUE TITLE
MADOUMONOGATARI                                                                                                 

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#709]
version:2.12.0
device:SCV39
cpu_type:3
video_type:2
comment:魔導物語 設定で、OPEN GL描画だと、戦闘突入と同時にフリーズします。ソフトウェア描画だと、重たいですが動作します。ですが、画面がフルサイズになります。
[state file](http://www.uoyabause.org//system/reports/state_files/000/005/335/original/T-6607G_2020_02_20_02_28_42.zip)
![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/005/335/original/screenshot.png?1582133326)

**Comment by devmiyax** [comment]
2020-02-22 10:04:56.131 29837-29837/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2020-02-22 10:04:56.131 29837-29837/? A/DEBUG: Build fingerprint: 'blackshark/SKW-H0/skywalker:9/SKYW1911010OS00MP5/bs.20191101.1537:user/release-keys'
2020-02-22 10:04:56.131 29837-29837/? A/DEBUG: Revision: '0'
2020-02-22 10:04:56.131 29837-29837/? A/DEBUG: ABI: 'arm64'
2020-02-22 10:04:56.131 29837-29837/? A/DEBUG: pid: 29514, tid: 29602, name: o:emulationmain  >>> org.uoyabause.uranus.pro:emulationmain <<<
2020-02-22 10:04:56.131 29837-29837/? A/DEBUG: Tombstone written to: pid: 29514, tid: 29602, name: o:emulationmain  >>> org.uoyabause.uranus.pro:emulationmain <<<
2020-02-22 10:04:56.131 29837-29837/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xbd00030181
2020-02-22 10:04:56.131 29837-29837/? A/DEBUG:     x0  000000bd00000161  x1  00000000f8060001  x2  000000779aa02f20  x3  0000000000006004
2020-02-22 10:04:56.131 29837-29837/? A/DEBUG:     x4  0000000000000000  x5  0000000000000000  x6  0000000000000001  x7  0000000000000000
2020-02-22 10:04:56.131 29837-29837/? A/DEBUG:     x8  0000000000000001  x9  0000000000000001  x10 0000000000000000  x11 0000000000000000
2020-02-22 10:04:56.131 29837-29837/? A/DEBUG:     x12 0000000000000000  x13 0000000000000001  x14 0000000000000001  x15 0000000000000000
2020-02-22 10:04:56.131 29837-29837/? A/DEBUG:     x16 0000000000000000  x17 0000000000000000  x18 0000000000000010  x19 000000779aa031b8
2020-02-22 10:04:56.131 29837-29837/? A/DEBUG:     x20 000000779aa02f28  x21 000000779aa031a8  x22 00000000f8060001  x23 000000779f709318
2020-02-22 10:04:56.131 29837-29837/? A/DEBUG:     x24 000000779aa02f20  x25 00000000fffffff8  x26 0000000000000000  x27 0000000000000000
2020-02-22 10:04:56.131 29837-29837/? A/DEBUG:     x28 000000779aa031b8  x29 000000779aa034b0
2020-02-22 10:04:56.131 29837-29837/? A/DEBUG:     sp  000000779aa02ee0  lr  000000779ebe41f0  pc  000000779ec0c460
2020-02-22 10:04:56.132 4732-18195/? E/HeadsetStateMachine: returning mCurrentState as Disconnected
2020-02-22 10:04:56.132 4732-18195/? E/HeadsetStateMachine: returning mCurrentState as Disconnected
2020-02-22 10:04:56.132 4732-18195/? E/HeadsetStateMachine: returning mCurrentState as Disconnected
2020-02-22 10:04:56.132 4732-18195/? E/HeadsetStateMachine: returning mCurrentState as Disconnected
2020-02-22 10:04:56.132 29837-29837/? A/DEBUG: backtrace:
2020-02-22 10:04:56.132 29837-29837/? A/DEBUG:     #00 pc 0000000000144460  /data/app/org.uoyabause.uranus.pro-WZMNI0NS22gQOLs3jkwffg==/lib/arm64/libyabause_native.so (YglIsCached+8)
2020-02-22 10:04:56.132 29837-29837/? A/DEBUG:     #01 pc 000000000011c1ec  /data/app/org.uoyabause.uranus.pro-WZMNI0NS22gQOLs3jkwffg==/lib/arm64/libyabause_native.so (Vdp2DrawPatternPos.constprop.23+368)
2020-02-22 10:04:56.132 29837-29837/? A/DEBUG:     #02 pc 000000000011d028  /data/app/org.uoyabause.uranus.pro-WZMNI0NS22gQOLs3jkwffg==/lib/arm64/libyabause_native.so (Vdp2DrawMapTest+736)
2020-02-22 10:04:56.132 29837-29837/? A/DEBUG:     #03 pc 0000000000121f7c  /data/app/org.uoyabause.uranus.pro-WZMNI0NS22gQOLs3jkwffg==/lib/arm64/libyabause_native.so (Vdp2DrawNBG3+1220)
2020-02-22 10:04:56.132 29837-29837/? A/DEBUG:     #04 pc 00000000001277f8  /data/app/org.uoyabause.uranus.pro-WZMNI0NS22gQOLs3jkwffg==/lib/arm64/libyabause_native.so (VIDOGLVdp2DrawScreens+3144)
2020-02-22 10:04:56.132 29837-29837/? A/DEBUG:     #05 pc 0000000000113c88  /data/app/org.uoyabause.uranus.pro-WZMNI0NS22gQOLs3jkwffg==/lib/arm64/libyabause_native.so (VdpProc+1928)
2020-02-22 10:04:56.132 29837-29837/? A/DEBUG:     #06 pc 00000000000922b8  /system/lib64/libc.so (__pthread_start(void*)+36)
2020-02-22 10:04:56.132 29837-29837/? A/DEBUG:     #07 pc 0000000000023bf8  /system/lib64/libc.so (__start_thread+68)

**Comment by devmiyax** [comment]
```
==8537==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x629000126928 at pc 0x55c16d2e77c8 bp 0x7ffd7fd71f70 sp 0x7ffd7fd71f60
WRITE of size 4 at 0x629000126928 thread T0
    #0 0x55c16d2e77c7 in VIDOGLVdp2DrawScreens (/home/devmiyax/yabasanshiro/yabause/build/src/qt/yabasanshiro+0x4e57c7)
    #1 0x55c16d28db60 in vdp2VBlankOUT (/home/devmiyax/yabasanshiro/yabause/build/src/qt/yabasanshiro+0x48bb60)
    #2 0x55c16d320274 in YabauseEmulate (/home/devmiyax/yabasanshiro/yabause/build/src/qt/yabasanshiro+0x51e274)
    #3 0x55c16d3204dc in YabauseExec (/home/devmiyax/yabasanshiro/yabause/build/src/qt/yabasanshiro+0x51e4dc)
    #4 0x55c16d02fb5c in PERQTHandleEvents (/home/devmiyax/yabasanshiro/yabause/build/src/qt/yabasanshiro+0x22db5c)
```
