### ISSUE TITLE
Launching using Android Intent doesn't work for 2.12.0

### ISSUE THREAD

**Issue by ReCoJav** [devmiyax/yabause#710]
As of the latest version (2.12.0) for both free and pro versions downloaded from the Play Store, launching using an Intent no longer works.

I'm using the Intent params provided below, which I was using for previous versions:

### Yaba Sanshiro Pro:

Target: org.uoyabause.android.pro/org.uoyabause.android.Yabause
Key: org.uoyabause.android.FileNameEx
Type: String
Value: absolute file path for a game CD-ROM ISO image

### Yaba Sanshiro Free:

Target: org.uoyabause.android/org.uoyabause.android.Yabause
Key: org.uoyabause.android.FileNameEx
Type: String
Value: absolute file path for a game CD-ROM ISO image

Here is an error log from when attempting to launch Yaba Sanshiro using an Intent:

### ERROR LOG:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.uoyabause.uranus.pro:emulationmain, PID: 26184
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.uoyabause.uranus.pro/org.uoyabause.android.Yabause}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.uoyabause.android.GameInfo.e' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3090)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6720)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.uoyabause.android.GameInfo.e' on a null object reference
        at org.uoyabause.android.Yabause.onCreate(Yabause.java:35)
        at android.app.Activity.performCreate(Activity.java:7179)
        at android.app.Activity.performCreate(Activity.java:7170)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2935)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3090) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6720) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

I've also tried launching using multiple Android frontends with the latest Play Store versions of Yaba Sanshiro Free and Pro, and app will not launch successfully there as well.

Hope this can be resolved soon!

Thank you!!! Keep up the good work with this awesome emulator!!!!

**Comment by devmiyax** [comment]
fixed int 3.3.1
