### ISSUE TITLE
dlopen failed: cannot locate symbol "rand" referenced by "libyabause.so"... On Game Load

### ISSUE THREAD

**Issue by SakadiwaaSoftware** [devmiyax/yabause#8]
I tried this Emulator on a Cloudnetgo C16 (RK3288 chipset TV box) and it crashes as soon as you select a game. I've attached a stacktrace if it's any help...

```
05-09 13:55:57.191    5180-5180/org.yabause.android E/dalvikvm﹕ dlopen("/data/app-lib/org.yabause.android-1/libyabause.so") failed: dlopen failed: cannot locate symbol "rand" referenced by "libyabause.so"...
05-09 13:55:57.191    5180-5180/org.yabause.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.yabause.android, PID: 5180
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "rand" referenced by "libyabause.so"...
            at java.lang.Runtime.loadLibrary(Runtime.java:364)
            at java.lang.System.loadLibrary(System.java:526)
            at org.yabause.android.Yabause.<clinit>(Yabause.java:447)
            at java.lang.Class.newInstanceImpl(Native Method)
            at java.lang.Class.newInstance(Class.java:1208)
            at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2112)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by devmiyax** [comment]
It seems that you success to buld Yabause-debug.apk but fail to build 
did you get the message below when you build?

```javascript
[armeabi] Gdbserver      : [arm-linux-androideabi-4.8] libs/armeabi/gdbserver
[armeabi] Gdbsetup       : libs/armeabi/gdb.setup
[armeabi] Compile thumb  : yabause <= yui.c
[armeabi] Compile thumb  : yabause <= sndaudiotrack.c
[armeabi] Compile thumb  : yabause <= sndopensl.c
[armeabi] Compile thumb  : yabause <= osdcore.c
[armeabi] SharedLibrary  : libyabause.so
[armeabi] Install        : libyabause.so => libs/armeabi/libyabause.so
```

**Comment by SegaNiGTHSRallyCCE** [comment]
Hello

I didn't build myself, I used the APK posted here:
http://forums.yabause.org/index.php?topic=1323.msg13583#msg13583

**Comment by SegaNiGTHSRallyCCE** [comment]
Same issue occurring on GPD Q9, another RK3288 chipset device..

05-28 20:05:00.221    8331-8331/org.yabause.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.yabause.android, PID: 8331
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "rand" referenced by "libyabause.so"...
            at java.lang.Runtime.loadLibrary(Runtime.java:364)
            at java.lang.System.loadLibrary(System.java:526)
            at org.yabause.android.Yabause.<clinit>(Yabause.java:447)
            at java.lang.Class.newInstanceImpl(Native Method)
            at java.lang.Class.newInstance(Class.java:1208)
            at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2101)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:811)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:627)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by devmiyax** [comment]
https://code.google.com/p/android-developer-preview/issues/detail?id=168


>To everyone having troubles with binaries compiled for L and running on <5.0 version, it's not related to the current issue.
>Binary compatibility isn't guaranteed for earlier versions than the one you're targeting. You should always target your app's minSDKVersion when using the NDK.


it seems that minSDKVersion down to Android 4.4

**Comment by devmiyax** [comment]
This issue may be solved by this changes.can you try again?
https://github.com/devmiyax/yabause/commit/04d07af80c5d7e66386512d60ea03292c6567ed3

**Comment by SegaNiGTHSRallyCCE** [comment]
Will be happy to test if you can provide an apk? :)
